### ISSUE TITLE
fix: hero section ux

### ISSUE THREAD

**Issue by aayushchugh** [richardevcom/memba#1]
Logo animation is running continuously. If we animate it only once, it'll provide better UX because currently user is distracted to that animation instead of the phone number that we are highlighting.

https://github.com/richardevcom/memba/assets/69336518/3633e106-08ff-4c48-a3d6-77e77893d07b

**Comment by richardevcom** [comment]
Haha, thank you man for suggestion. Although this is just a challange temp landing - I might update it to single, non-continuous loop then ;)
